# Generated by Django 2.2.7 on 2019-11-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20191106_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersprice',
            name='customer_id',
            field=models.IntegerField(default=None),
        ),
    ]
