# Generated by Django 2.2.7 on 2019-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customersprice_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprice',
            name='customer_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
