# Generated by Django 2.2.7 on 2019-11-06 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20191106_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprice',
            name='customer_id',
            field=models.IntegerField(default=None, max_length=100),
        ),
    ]
