# Generated by Django 2.2.7 on 2019-11-07 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20191107_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersprice',
            name='customer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='customers.Customers'),
        ),
    ]
