# Generated by Django 2.2.7 on 2019-11-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20191107_0811'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
