# Generated by Django 3.0.5 on 2020-04-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='user.svg', upload_to='./'),
        ),
    ]
