# Generated by Django 2.2.7 on 2019-11-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20191121_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='media/boxer-prime-intro.jpg', upload_to='media/'),
        ),
    ]
