# Generated by Django 2.2.7 on 2019-11-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20191122_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='/static/images/boxer-prime-intro.jpg', upload_to='media/'),
        ),
    ]
