# Generated by Django 2.2.7 on 2019-11-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20191125_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(default='a.jpg', upload_to='banana/'),
        ),
    ]
