# Generated by Django 3.0 on 2019-12-13 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20191202_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatus',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Bookings'),
        ),
    ]
