# Generated by Django 3.0.1 on 2019-12-19 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20191217_0653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='endtime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='starttime',
            new_name='start_time',
        ),
    ]
