# Generated by Django 3.0.1 on 2020-01-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20191219_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='start_time',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
