# Generated by Django 3.0.1 on 2020-01-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_auto_20200123_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='start_time',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
