# Generated by Django 3.0.1 on 2020-01-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_auto_20200123_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
