# Generated by Django 3.0.1 on 2020-01-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20200123_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='dates',
        ),
    ]
