# Generated by Django 3.0.1 on 2020-01-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_auto_20200123_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
