# Generated by Django 3.0.2 on 2020-01-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_bookings_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='start_time',
        ),
        migrations.AddField(
            model_name='bookings',
            name='timeEnd',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='timeStart',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
