# Generated by Django 3.0.2 on 2020-01-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0015_auto_20200130_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='end_time',
            new_name='endTime',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
