# Generated by Django 3.0.2 on 2020-01-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0016_auto_20200130_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='field',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
