# Generated by Django 3.0.2 on 2020-01-30 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0017_bookings_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='startTime',
        ),
    ]
