# Generated by Django 3.0.2 on 2020-01-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0018_auto_20200130_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='endTime',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='startTime',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
