# Generated by Django 3.0.2 on 2020-01-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0019_auto_20200130_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='endTime',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='bookings',
            old_name='startTime',
            new_name='start_time',
        ),
    ]
