# Generated by Django 3.0.2 on 2020-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0020_auto_20200130_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='field',
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
