# Generated by Django 3.0.2 on 2020-02-11 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0021_auto_20200207_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatus',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.Bookings'),
        ),
    ]
