# Generated by Django 3.0.5 on 2020-04-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0024_auto_20200426_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=None, max_length=100, null=True),
        ),
    ]
